level-0:
  C: 10000
  class_weights: true
  max_iter: 10
  model: LogReg
  single-point-node: DecisionTree
level-1:
  C: 10000
  class_weights: true
  max_iter: 10
  model: LogReg
  single-point-node: DecisionTree
level-2:
  C: 10000
  class_weights: true
  max_iter: 5
  model: LogReg
  single-point-node: DecisionTree
