{'setup': 'lmi-test',
 'data': {'data-dir': '/storage/brno12-cerit/home/tslaninakova/data/test',
  'dataset-file': 'simple-data.csv',
  'queries': 'simple-queries.txt',
  'knn-gt': 'simple-knn.json',
  'labels-dir': 'labels/',
  'pivots-filename': 'pivots/M-tree.struct',
  'normalize': False,
  'shuffle': True},
 'LMI': {
     'model-config': './supplementary-experiment-setups/data-driven/models/model-kmeans.yml',
     'n_levels': 2,
     'training-dataset-percentage': 1},
 'experiment': {'output-dir': 'outputs',
  'search-stop-conditions': [0.0005,
   0.001,
   0.003,
   0.005,
   0.01,
   0.05,
   0.1,
   0.2,
   0.3,
   0.5],
  'knns': 30}}
