level-0:
  model: MultilabelNN
  epochs: 10
  learning_rate: 0.001
  optimizer: adam
  loss: 'categorical_crossentropy'
  hidden_layers:
    dense:
      - units: 282
        activation: relu
        dropout: null
      - units: 1024
        activation: relu
        dropout: null
      - units: 256
        activation: relu
        dropout: null
level-1:
  model: MultilabelNN
  epochs: 10
  learning_rate: 0.01
  optimizer: adam
  loss: 'categorical_crossentropy'
  hidden_layers:
    dense:
      - units: 282
        activation: relu
        dropout: null
      - units: 1024
        activation: relu
        dropout: null
      - units: 256
        activation: relu
        dropout: null