level-0:
  model: MultilabelNN
  epochs: 20
  learning_rate: 0.0001
  optimizer: adam
  loss: 'categorical_crossentropy'
  hidden_layers:
    dense:
      - units: 282
        activation: relu
        dropout: null
      - units: 1024
        activation: relu
        dropout: null
      - units: 512
        activation: relu
        dropout: null
      - units: 256
        activation: relu
        dropout: null
level-1:
  model: MultilabelNN
  epochs: 3
  learning_rate: 0.0001
  optimizer: adam
  loss: 'categorical_crossentropy'
  hidden_layers:
    dense:
      - units: 282
        activation: relu
        dropout: null
      - units: 1024
        activation: relu
        dropout: null
      - units: 512
        activation: relu
        dropout: null
      - units: 256
        activation: relu
        dropout: null