level-0:
  epochs: 20
  hidden_layers:
    dense:
    - activation: relu
      dropout: null
      units: 282
    - activation: relu
      dropout: null
      units: 1024
    - activation: relu
      dropout: null
      units: 512
    - activation: relu
      dropout: null
      units: 256
  learning_rate: 0.0001
  loss: categorical_crossentropy
  model: MultilabelNN
  optimizer: adam
level-1:
  epochs: 3
  hidden_layers:
    dense:
    - activation: relu
      dropout: null
      units: 282
    - activation: relu
      dropout: null
      units: 1024
    - activation: relu
      dropout: null
      units: 512
    - activation: relu
      dropout: null
      units: 256
  learning_rate: 0.0001
  loss: categorical_crossentropy
  model: MultilabelNN
  optimizer: adam
