level-0:
  epochs: 1
  hidden_layers:
    dense:
    - activation: relu
      dropout: null
      units: 282
    - activation: relu
      dropout: null
      units: 128
  learning_rate: 0.0001
  loss: sparse_categorical_crossentropy
  model: NN
  optimizer: adam
level-1:
  epochs: 1
  hidden_layers:
    dense:
    - activation: relu
      dropout: null
      units: 282
    - activation: relu
      dropout: null
      units: 128
  learning_rate: 0.0001
  loss: sparse_categorical_crossentropy
  model: NN
  optimizer: adam